/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Scrum Bot API
 * The Scrum Bot API description
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import { customInstance } from '.././axios';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export type summariesControllerListSummariesResponse200 = {
  data: void
  status: 200
}
    
export type summariesControllerListSummariesResponseSuccess = (summariesControllerListSummariesResponse200) & {
  headers: Headers;
};
;

export type summariesControllerListSummariesResponse = (summariesControllerListSummariesResponseSuccess)

export const getSummariesControllerListSummariesUrl = () => {


  

  return `/api/summaries`
}

export const summariesControllerListSummaries = async ( options?: RequestInit): Promise<summariesControllerListSummariesResponse> => {
  
  return customInstance<summariesControllerListSummariesResponse>(getSummariesControllerListSummariesUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getSummariesControllerListSummariesQueryKey = () => {
    return [
    `/api/summaries`
    ] as const;
    }

    
export const getSummariesControllerListSummariesQueryOptions = <TData = Awaited<ReturnType<typeof summariesControllerListSummaries>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof summariesControllerListSummaries>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getSummariesControllerListSummariesQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof summariesControllerListSummaries>>> = ({ signal }) => summariesControllerListSummaries({ signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof summariesControllerListSummaries>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type SummariesControllerListSummariesQueryResult = NonNullable<Awaited<ReturnType<typeof summariesControllerListSummaries>>>
export type SummariesControllerListSummariesQueryError = unknown


export function useSummariesControllerListSummaries<TData = Awaited<ReturnType<typeof summariesControllerListSummaries>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof summariesControllerListSummaries>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof summariesControllerListSummaries>>,
          TError,
          Awaited<ReturnType<typeof summariesControllerListSummaries>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSummariesControllerListSummaries<TData = Awaited<ReturnType<typeof summariesControllerListSummaries>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof summariesControllerListSummaries>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof summariesControllerListSummaries>>,
          TError,
          Awaited<ReturnType<typeof summariesControllerListSummaries>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSummariesControllerListSummaries<TData = Awaited<ReturnType<typeof summariesControllerListSummaries>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof summariesControllerListSummaries>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useSummariesControllerListSummaries<TData = Awaited<ReturnType<typeof summariesControllerListSummaries>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof summariesControllerListSummaries>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getSummariesControllerListSummariesQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export type summariesControllerSummarizeResponse201 = {
  data: void
  status: 201
}
    
export type summariesControllerSummarizeResponseSuccess = (summariesControllerSummarizeResponse201) & {
  headers: Headers;
};
;

export type summariesControllerSummarizeResponse = (summariesControllerSummarizeResponseSuccess)

export const getSummariesControllerSummarizeUrl = () => {


  

  return `/api/summarize`
}

export const summariesControllerSummarize = async ( options?: RequestInit): Promise<summariesControllerSummarizeResponse> => {
  
  return customInstance<summariesControllerSummarizeResponse>(getSummariesControllerSummarizeUrl(),
  {      
    ...options,
    method: 'POST'
    
    
  }
);}




export const getSummariesControllerSummarizeMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof summariesControllerSummarize>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof summariesControllerSummarize>>, TError,void, TContext> => {

const mutationKey = ['summariesControllerSummarize'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof summariesControllerSummarize>>, void> = () => {
          

          return  summariesControllerSummarize(requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type SummariesControllerSummarizeMutationResult = NonNullable<Awaited<ReturnType<typeof summariesControllerSummarize>>>
    
    export type SummariesControllerSummarizeMutationError = unknown

    export const useSummariesControllerSummarize = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof summariesControllerSummarize>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof summariesControllerSummarize>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getSummariesControllerSummarizeMutationOptions(options), queryClient);
    }
    