/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Scrum Bot API
 * The Scrum Bot API description
 * OpenAPI spec version: 1.0
 */

export type DraftsControllerListDraftsParams = {
  status?: string;
  type?: string;
  page?: number;
  limit?: number;
};
