/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Scrum Bot API
 * The Scrum Bot API description
 * OpenAPI spec version: 1.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  DecisionsControllerListDecisionsParams
} from '.././model';

import { customInstance } from '.././axios';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export type decisionsControllerListDecisionsResponse200 = {
  data: void
  status: 200
}
    
export type decisionsControllerListDecisionsResponseSuccess = (decisionsControllerListDecisionsResponse200) & {
  headers: Headers;
};
;

export type decisionsControllerListDecisionsResponse = (decisionsControllerListDecisionsResponseSuccess)

export const getDecisionsControllerListDecisionsUrl = (params: DecisionsControllerListDecisionsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/decisions?${stringifiedParams}` : `/api/decisions`
}

export const decisionsControllerListDecisions = async (params: DecisionsControllerListDecisionsParams, options?: RequestInit): Promise<decisionsControllerListDecisionsResponse> => {
  
  return customInstance<decisionsControllerListDecisionsResponse>(getDecisionsControllerListDecisionsUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getDecisionsControllerListDecisionsQueryKey = (params?: DecisionsControllerListDecisionsParams,) => {
    return [
    `/api/decisions`, ...(params ? [params] : [])
    ] as const;
    }

    
export const getDecisionsControllerListDecisionsQueryOptions = <TData = Awaited<ReturnType<typeof decisionsControllerListDecisions>>, TError = unknown>(params: DecisionsControllerListDecisionsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof decisionsControllerListDecisions>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getDecisionsControllerListDecisionsQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof decisionsControllerListDecisions>>> = ({ signal }) => decisionsControllerListDecisions(params, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof decisionsControllerListDecisions>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type DecisionsControllerListDecisionsQueryResult = NonNullable<Awaited<ReturnType<typeof decisionsControllerListDecisions>>>
export type DecisionsControllerListDecisionsQueryError = unknown


export function useDecisionsControllerListDecisions<TData = Awaited<ReturnType<typeof decisionsControllerListDecisions>>, TError = unknown>(
 params: DecisionsControllerListDecisionsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof decisionsControllerListDecisions>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof decisionsControllerListDecisions>>,
          TError,
          Awaited<ReturnType<typeof decisionsControllerListDecisions>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useDecisionsControllerListDecisions<TData = Awaited<ReturnType<typeof decisionsControllerListDecisions>>, TError = unknown>(
 params: DecisionsControllerListDecisionsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof decisionsControllerListDecisions>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof decisionsControllerListDecisions>>,
          TError,
          Awaited<ReturnType<typeof decisionsControllerListDecisions>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useDecisionsControllerListDecisions<TData = Awaited<ReturnType<typeof decisionsControllerListDecisions>>, TError = unknown>(
 params: DecisionsControllerListDecisionsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof decisionsControllerListDecisions>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useDecisionsControllerListDecisions<TData = Awaited<ReturnType<typeof decisionsControllerListDecisions>>, TError = unknown>(
 params: DecisionsControllerListDecisionsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof decisionsControllerListDecisions>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getDecisionsControllerListDecisionsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export type decisionsControllerGetDecisionResponse200 = {
  data: void
  status: 200
}
    
export type decisionsControllerGetDecisionResponseSuccess = (decisionsControllerGetDecisionResponse200) & {
  headers: Headers;
};
;

export type decisionsControllerGetDecisionResponse = (decisionsControllerGetDecisionResponseSuccess)

export const getDecisionsControllerGetDecisionUrl = (id: string,) => {


  

  return `/api/decisions/${id}`
}

export const decisionsControllerGetDecision = async (id: string, options?: RequestInit): Promise<decisionsControllerGetDecisionResponse> => {
  
  return customInstance<decisionsControllerGetDecisionResponse>(getDecisionsControllerGetDecisionUrl(id),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getDecisionsControllerGetDecisionQueryKey = (id: string,) => {
    return [
    `/api/decisions/${id}`
    ] as const;
    }

    
export const getDecisionsControllerGetDecisionQueryOptions = <TData = Awaited<ReturnType<typeof decisionsControllerGetDecision>>, TError = unknown>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof decisionsControllerGetDecision>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getDecisionsControllerGetDecisionQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof decisionsControllerGetDecision>>> = ({ signal }) => decisionsControllerGetDecision(id, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof decisionsControllerGetDecision>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type DecisionsControllerGetDecisionQueryResult = NonNullable<Awaited<ReturnType<typeof decisionsControllerGetDecision>>>
export type DecisionsControllerGetDecisionQueryError = unknown


export function useDecisionsControllerGetDecision<TData = Awaited<ReturnType<typeof decisionsControllerGetDecision>>, TError = unknown>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof decisionsControllerGetDecision>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof decisionsControllerGetDecision>>,
          TError,
          Awaited<ReturnType<typeof decisionsControllerGetDecision>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useDecisionsControllerGetDecision<TData = Awaited<ReturnType<typeof decisionsControllerGetDecision>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof decisionsControllerGetDecision>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof decisionsControllerGetDecision>>,
          TError,
          Awaited<ReturnType<typeof decisionsControllerGetDecision>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useDecisionsControllerGetDecision<TData = Awaited<ReturnType<typeof decisionsControllerGetDecision>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof decisionsControllerGetDecision>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useDecisionsControllerGetDecision<TData = Awaited<ReturnType<typeof decisionsControllerGetDecision>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof decisionsControllerGetDecision>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getDecisionsControllerGetDecisionQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




