/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Scrum Bot API
 * The Scrum Bot API description
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  DraftsControllerListDraftsParams
} from '.././model';

import { customInstance } from '.././axios';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export type draftsControllerListDraftsResponse200 = {
  data: void
  status: 200
}
    
export type draftsControllerListDraftsResponseSuccess = (draftsControllerListDraftsResponse200) & {
  headers: Headers;
};
;

export type draftsControllerListDraftsResponse = (draftsControllerListDraftsResponseSuccess)

export const getDraftsControllerListDraftsUrl = (params: DraftsControllerListDraftsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/drafts?${stringifiedParams}` : `/api/drafts`
}

export const draftsControllerListDrafts = async (params: DraftsControllerListDraftsParams, options?: RequestInit): Promise<draftsControllerListDraftsResponse> => {
  
  return customInstance<draftsControllerListDraftsResponse>(getDraftsControllerListDraftsUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getDraftsControllerListDraftsQueryKey = (params?: DraftsControllerListDraftsParams,) => {
    return [
    `/api/drafts`, ...(params ? [params] : [])
    ] as const;
    }

    
export const getDraftsControllerListDraftsQueryOptions = <TData = Awaited<ReturnType<typeof draftsControllerListDrafts>>, TError = unknown>(params: DraftsControllerListDraftsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof draftsControllerListDrafts>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getDraftsControllerListDraftsQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof draftsControllerListDrafts>>> = ({ signal }) => draftsControllerListDrafts(params, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof draftsControllerListDrafts>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type DraftsControllerListDraftsQueryResult = NonNullable<Awaited<ReturnType<typeof draftsControllerListDrafts>>>
export type DraftsControllerListDraftsQueryError = unknown


export function useDraftsControllerListDrafts<TData = Awaited<ReturnType<typeof draftsControllerListDrafts>>, TError = unknown>(
 params: DraftsControllerListDraftsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof draftsControllerListDrafts>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof draftsControllerListDrafts>>,
          TError,
          Awaited<ReturnType<typeof draftsControllerListDrafts>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useDraftsControllerListDrafts<TData = Awaited<ReturnType<typeof draftsControllerListDrafts>>, TError = unknown>(
 params: DraftsControllerListDraftsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof draftsControllerListDrafts>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof draftsControllerListDrafts>>,
          TError,
          Awaited<ReturnType<typeof draftsControllerListDrafts>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useDraftsControllerListDrafts<TData = Awaited<ReturnType<typeof draftsControllerListDrafts>>, TError = unknown>(
 params: DraftsControllerListDraftsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof draftsControllerListDrafts>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useDraftsControllerListDrafts<TData = Awaited<ReturnType<typeof draftsControllerListDrafts>>, TError = unknown>(
 params: DraftsControllerListDraftsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof draftsControllerListDrafts>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getDraftsControllerListDraftsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export type draftsControllerGetDraftResponse200 = {
  data: void
  status: 200
}
    
export type draftsControllerGetDraftResponseSuccess = (draftsControllerGetDraftResponse200) & {
  headers: Headers;
};
;

export type draftsControllerGetDraftResponse = (draftsControllerGetDraftResponseSuccess)

export const getDraftsControllerGetDraftUrl = (id: string,) => {


  

  return `/api/drafts/${id}`
}

export const draftsControllerGetDraft = async (id: string, options?: RequestInit): Promise<draftsControllerGetDraftResponse> => {
  
  return customInstance<draftsControllerGetDraftResponse>(getDraftsControllerGetDraftUrl(id),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getDraftsControllerGetDraftQueryKey = (id: string,) => {
    return [
    `/api/drafts/${id}`
    ] as const;
    }

    
export const getDraftsControllerGetDraftQueryOptions = <TData = Awaited<ReturnType<typeof draftsControllerGetDraft>>, TError = unknown>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof draftsControllerGetDraft>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getDraftsControllerGetDraftQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof draftsControllerGetDraft>>> = ({ signal }) => draftsControllerGetDraft(id, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof draftsControllerGetDraft>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type DraftsControllerGetDraftQueryResult = NonNullable<Awaited<ReturnType<typeof draftsControllerGetDraft>>>
export type DraftsControllerGetDraftQueryError = unknown


export function useDraftsControllerGetDraft<TData = Awaited<ReturnType<typeof draftsControllerGetDraft>>, TError = unknown>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof draftsControllerGetDraft>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof draftsControllerGetDraft>>,
          TError,
          Awaited<ReturnType<typeof draftsControllerGetDraft>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useDraftsControllerGetDraft<TData = Awaited<ReturnType<typeof draftsControllerGetDraft>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof draftsControllerGetDraft>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof draftsControllerGetDraft>>,
          TError,
          Awaited<ReturnType<typeof draftsControllerGetDraft>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useDraftsControllerGetDraft<TData = Awaited<ReturnType<typeof draftsControllerGetDraft>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof draftsControllerGetDraft>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useDraftsControllerGetDraft<TData = Awaited<ReturnType<typeof draftsControllerGetDraft>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof draftsControllerGetDraft>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getDraftsControllerGetDraftQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export type draftsControllerUpdateDraftResponse200 = {
  data: void
  status: 200
}
    
export type draftsControllerUpdateDraftResponseSuccess = (draftsControllerUpdateDraftResponse200) & {
  headers: Headers;
};
;

export type draftsControllerUpdateDraftResponse = (draftsControllerUpdateDraftResponseSuccess)

export const getDraftsControllerUpdateDraftUrl = (id: string,) => {


  

  return `/api/drafts/${id}`
}

export const draftsControllerUpdateDraft = async (id: string, options?: RequestInit): Promise<draftsControllerUpdateDraftResponse> => {
  
  return customInstance<draftsControllerUpdateDraftResponse>(getDraftsControllerUpdateDraftUrl(id),
  {      
    ...options,
    method: 'PATCH'
    
    
  }
);}




export const getDraftsControllerUpdateDraftMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof draftsControllerUpdateDraft>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof draftsControllerUpdateDraft>>, TError,{id: string}, TContext> => {

const mutationKey = ['draftsControllerUpdateDraft'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof draftsControllerUpdateDraft>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  draftsControllerUpdateDraft(id,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type DraftsControllerUpdateDraftMutationResult = NonNullable<Awaited<ReturnType<typeof draftsControllerUpdateDraft>>>
    
    export type DraftsControllerUpdateDraftMutationError = unknown

    export const useDraftsControllerUpdateDraft = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof draftsControllerUpdateDraft>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof draftsControllerUpdateDraft>>,
        TError,
        {id: string},
        TContext
      > => {
      return useMutation(getDraftsControllerUpdateDraftMutationOptions(options), queryClient);
    }
    export type draftsControllerApproveDraftResponse201 = {
  data: void
  status: 201
}
    
export type draftsControllerApproveDraftResponseSuccess = (draftsControllerApproveDraftResponse201) & {
  headers: Headers;
};
;

export type draftsControllerApproveDraftResponse = (draftsControllerApproveDraftResponseSuccess)

export const getDraftsControllerApproveDraftUrl = (id: string,) => {


  

  return `/api/drafts/${id}/approve`
}

export const draftsControllerApproveDraft = async (id: string, options?: RequestInit): Promise<draftsControllerApproveDraftResponse> => {
  
  return customInstance<draftsControllerApproveDraftResponse>(getDraftsControllerApproveDraftUrl(id),
  {      
    ...options,
    method: 'POST'
    
    
  }
);}




export const getDraftsControllerApproveDraftMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof draftsControllerApproveDraft>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof draftsControllerApproveDraft>>, TError,{id: string}, TContext> => {

const mutationKey = ['draftsControllerApproveDraft'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof draftsControllerApproveDraft>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  draftsControllerApproveDraft(id,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type DraftsControllerApproveDraftMutationResult = NonNullable<Awaited<ReturnType<typeof draftsControllerApproveDraft>>>
    
    export type DraftsControllerApproveDraftMutationError = unknown

    export const useDraftsControllerApproveDraft = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof draftsControllerApproveDraft>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof draftsControllerApproveDraft>>,
        TError,
        {id: string},
        TContext
      > => {
      return useMutation(getDraftsControllerApproveDraftMutationOptions(options), queryClient);
    }
    export type draftsControllerRejectDraftResponse201 = {
  data: void
  status: 201
}
    
export type draftsControllerRejectDraftResponseSuccess = (draftsControllerRejectDraftResponse201) & {
  headers: Headers;
};
;

export type draftsControllerRejectDraftResponse = (draftsControllerRejectDraftResponseSuccess)

export const getDraftsControllerRejectDraftUrl = (id: string,) => {


  

  return `/api/drafts/${id}/reject`
}

export const draftsControllerRejectDraft = async (id: string, options?: RequestInit): Promise<draftsControllerRejectDraftResponse> => {
  
  return customInstance<draftsControllerRejectDraftResponse>(getDraftsControllerRejectDraftUrl(id),
  {      
    ...options,
    method: 'POST'
    
    
  }
);}




export const getDraftsControllerRejectDraftMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof draftsControllerRejectDraft>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof draftsControllerRejectDraft>>, TError,{id: string}, TContext> => {

const mutationKey = ['draftsControllerRejectDraft'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof draftsControllerRejectDraft>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  draftsControllerRejectDraft(id,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type DraftsControllerRejectDraftMutationResult = NonNullable<Awaited<ReturnType<typeof draftsControllerRejectDraft>>>
    
    export type DraftsControllerRejectDraftMutationError = unknown

    export const useDraftsControllerRejectDraft = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof draftsControllerRejectDraft>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof draftsControllerRejectDraft>>,
        TError,
        {id: string},
        TContext
      > => {
      return useMutation(getDraftsControllerRejectDraftMutationOptions(options), queryClient);
    }
    