/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Scrum Bot API
 * The Scrum Bot API description
 * OpenAPI spec version: 1.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import { customInstance } from '.././axios';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export type runsControllerGetRunResponse200 = {
  data: void
  status: 200
}
    
export type runsControllerGetRunResponseSuccess = (runsControllerGetRunResponse200) & {
  headers: Headers;
};
;

export type runsControllerGetRunResponse = (runsControllerGetRunResponseSuccess)

export const getRunsControllerGetRunUrl = (runId: string,) => {


  

  return `/api/runs/${runId}`
}

export const runsControllerGetRun = async (runId: string, options?: RequestInit): Promise<runsControllerGetRunResponse> => {
  
  return customInstance<runsControllerGetRunResponse>(getRunsControllerGetRunUrl(runId),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getRunsControllerGetRunQueryKey = (runId: string,) => {
    return [
    `/api/runs/${runId}`
    ] as const;
    }

    
export const getRunsControllerGetRunQueryOptions = <TData = Awaited<ReturnType<typeof runsControllerGetRun>>, TError = unknown>(runId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof runsControllerGetRun>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getRunsControllerGetRunQueryKey(runId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof runsControllerGetRun>>> = ({ signal }) => runsControllerGetRun(runId, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(runId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof runsControllerGetRun>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type RunsControllerGetRunQueryResult = NonNullable<Awaited<ReturnType<typeof runsControllerGetRun>>>
export type RunsControllerGetRunQueryError = unknown


export function useRunsControllerGetRun<TData = Awaited<ReturnType<typeof runsControllerGetRun>>, TError = unknown>(
 runId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof runsControllerGetRun>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof runsControllerGetRun>>,
          TError,
          Awaited<ReturnType<typeof runsControllerGetRun>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useRunsControllerGetRun<TData = Awaited<ReturnType<typeof runsControllerGetRun>>, TError = unknown>(
 runId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof runsControllerGetRun>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof runsControllerGetRun>>,
          TError,
          Awaited<ReturnType<typeof runsControllerGetRun>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useRunsControllerGetRun<TData = Awaited<ReturnType<typeof runsControllerGetRun>>, TError = unknown>(
 runId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof runsControllerGetRun>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useRunsControllerGetRun<TData = Awaited<ReturnType<typeof runsControllerGetRun>>, TError = unknown>(
 runId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof runsControllerGetRun>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getRunsControllerGetRunQueryOptions(runId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export type runsControllerStreamRunResponse200 = {
  data: void
  status: 200
}
    
export type runsControllerStreamRunResponseSuccess = (runsControllerStreamRunResponse200) & {
  headers: Headers;
};
;

export type runsControllerStreamRunResponse = (runsControllerStreamRunResponseSuccess)

export const getRunsControllerStreamRunUrl = (runId: string,) => {


  

  return `/api/runs/${runId}/stream`
}

export const runsControllerStreamRun = async (runId: string, options?: RequestInit): Promise<runsControllerStreamRunResponse> => {
  
  return customInstance<runsControllerStreamRunResponse>(getRunsControllerStreamRunUrl(runId),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getRunsControllerStreamRunQueryKey = (runId: string,) => {
    return [
    `/api/runs/${runId}/stream`
    ] as const;
    }

    
export const getRunsControllerStreamRunQueryOptions = <TData = Awaited<ReturnType<typeof runsControllerStreamRun>>, TError = unknown>(runId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof runsControllerStreamRun>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getRunsControllerStreamRunQueryKey(runId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof runsControllerStreamRun>>> = ({ signal }) => runsControllerStreamRun(runId, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(runId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof runsControllerStreamRun>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type RunsControllerStreamRunQueryResult = NonNullable<Awaited<ReturnType<typeof runsControllerStreamRun>>>
export type RunsControllerStreamRunQueryError = unknown


export function useRunsControllerStreamRun<TData = Awaited<ReturnType<typeof runsControllerStreamRun>>, TError = unknown>(
 runId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof runsControllerStreamRun>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof runsControllerStreamRun>>,
          TError,
          Awaited<ReturnType<typeof runsControllerStreamRun>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useRunsControllerStreamRun<TData = Awaited<ReturnType<typeof runsControllerStreamRun>>, TError = unknown>(
 runId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof runsControllerStreamRun>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof runsControllerStreamRun>>,
          TError,
          Awaited<ReturnType<typeof runsControllerStreamRun>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useRunsControllerStreamRun<TData = Awaited<ReturnType<typeof runsControllerStreamRun>>, TError = unknown>(
 runId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof runsControllerStreamRun>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useRunsControllerStreamRun<TData = Awaited<ReturnType<typeof runsControllerStreamRun>>, TError = unknown>(
 runId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof runsControllerStreamRun>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getRunsControllerStreamRunQueryOptions(runId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




