/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Scrum Bot API
 * The Scrum Bot API description
 * OpenAPI spec version: 1.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  EventsControllerListEventsParams
} from '.././model';

import { customInstance } from '.././axios';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export type eventsControllerListEventsResponse200 = {
  data: void
  status: 200
}
    
export type eventsControllerListEventsResponseSuccess = (eventsControllerListEventsResponse200) & {
  headers: Headers;
};
;

export type eventsControllerListEventsResponse = (eventsControllerListEventsResponseSuccess)

export const getEventsControllerListEventsUrl = (params: EventsControllerListEventsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/events?${stringifiedParams}` : `/api/events`
}

export const eventsControllerListEvents = async (params: EventsControllerListEventsParams, options?: RequestInit): Promise<eventsControllerListEventsResponse> => {
  
  return customInstance<eventsControllerListEventsResponse>(getEventsControllerListEventsUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getEventsControllerListEventsQueryKey = (params?: EventsControllerListEventsParams,) => {
    return [
    `/api/events`, ...(params ? [params] : [])
    ] as const;
    }

    
export const getEventsControllerListEventsQueryOptions = <TData = Awaited<ReturnType<typeof eventsControllerListEvents>>, TError = unknown>(params: EventsControllerListEventsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof eventsControllerListEvents>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getEventsControllerListEventsQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof eventsControllerListEvents>>> = ({ signal }) => eventsControllerListEvents(params, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof eventsControllerListEvents>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type EventsControllerListEventsQueryResult = NonNullable<Awaited<ReturnType<typeof eventsControllerListEvents>>>
export type EventsControllerListEventsQueryError = unknown


export function useEventsControllerListEvents<TData = Awaited<ReturnType<typeof eventsControllerListEvents>>, TError = unknown>(
 params: EventsControllerListEventsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof eventsControllerListEvents>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof eventsControllerListEvents>>,
          TError,
          Awaited<ReturnType<typeof eventsControllerListEvents>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useEventsControllerListEvents<TData = Awaited<ReturnType<typeof eventsControllerListEvents>>, TError = unknown>(
 params: EventsControllerListEventsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof eventsControllerListEvents>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof eventsControllerListEvents>>,
          TError,
          Awaited<ReturnType<typeof eventsControllerListEvents>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useEventsControllerListEvents<TData = Awaited<ReturnType<typeof eventsControllerListEvents>>, TError = unknown>(
 params: EventsControllerListEventsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof eventsControllerListEvents>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useEventsControllerListEvents<TData = Awaited<ReturnType<typeof eventsControllerListEvents>>, TError = unknown>(
 params: EventsControllerListEventsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof eventsControllerListEvents>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getEventsControllerListEventsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




