/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * Scrum Bot API
 * The Scrum Bot API description
 * OpenAPI spec version: 1.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CostControllerGetCostsParams
} from '.././model';

import { customInstance } from '.././axios';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export type costControllerGetCostsResponse200 = {
  data: void
  status: 200
}
    
export type costControllerGetCostsResponseSuccess = (costControllerGetCostsResponse200) & {
  headers: Headers;
};
;

export type costControllerGetCostsResponse = (costControllerGetCostsResponseSuccess)

export const getCostControllerGetCostsUrl = (params: CostControllerGetCostsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/cost?${stringifiedParams}` : `/api/cost`
}

export const costControllerGetCosts = async (params: CostControllerGetCostsParams, options?: RequestInit): Promise<costControllerGetCostsResponse> => {
  
  return customInstance<costControllerGetCostsResponse>(getCostControllerGetCostsUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getCostControllerGetCostsQueryKey = (params?: CostControllerGetCostsParams,) => {
    return [
    `/api/cost`, ...(params ? [params] : [])
    ] as const;
    }

    
export const getCostControllerGetCostsQueryOptions = <TData = Awaited<ReturnType<typeof costControllerGetCosts>>, TError = unknown>(params: CostControllerGetCostsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof costControllerGetCosts>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getCostControllerGetCostsQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof costControllerGetCosts>>> = ({ signal }) => costControllerGetCosts(params, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof costControllerGetCosts>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type CostControllerGetCostsQueryResult = NonNullable<Awaited<ReturnType<typeof costControllerGetCosts>>>
export type CostControllerGetCostsQueryError = unknown


export function useCostControllerGetCosts<TData = Awaited<ReturnType<typeof costControllerGetCosts>>, TError = unknown>(
 params: CostControllerGetCostsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof costControllerGetCosts>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof costControllerGetCosts>>,
          TError,
          Awaited<ReturnType<typeof costControllerGetCosts>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useCostControllerGetCosts<TData = Awaited<ReturnType<typeof costControllerGetCosts>>, TError = unknown>(
 params: CostControllerGetCostsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof costControllerGetCosts>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof costControllerGetCosts>>,
          TError,
          Awaited<ReturnType<typeof costControllerGetCosts>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useCostControllerGetCosts<TData = Awaited<ReturnType<typeof costControllerGetCosts>>, TError = unknown>(
 params: CostControllerGetCostsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof costControllerGetCosts>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useCostControllerGetCosts<TData = Awaited<ReturnType<typeof costControllerGetCosts>>, TError = unknown>(
 params: CostControllerGetCostsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof costControllerGetCosts>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getCostControllerGetCostsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




